# A test workflow to check that the deploy-to-aws workflow works
name: deploy-to-aws test workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # schedules this to run weekly
  # schedule:
  #   - cron: '5 3 * * 0' # At 03:05 on Sunday
  push:
    branches: [main]
  pull_request:
    branches: [main]    

jobs:
  call-test-workflow:
    strategy:
      matrix:
        node-pkg-manager: [npm, yarn2]    
    uses: ./.github/workflows/deploy-to-aws.yml
    with:
      python-version:  3.11
      working-directory: samplePythonProject
      aws-login: false
      smoketest-query: 'query Query {country(code: "NZ") {capital}}'
      smoketest-expected: 'Wellington'
      node-pkg-manager: ${{ matrix.node-pkg-manager }}
    secrets: inherit
