name: Python Deploy Docs

on:
  workflow_call:
    inputs:
        python-version:
            description: The python version to use
            required: true
            type: string
            default: "3.10"
        poetry-version:
            description: The poetry version to use
            required: false
            type: string
            default: "latest"
        working-directory:
            description: The working directory
            required: false
            type: string
            default: .


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ${{ inputs.working-directory }}

    steps:

      - uses: actions/checkout@v4

      - name: install_package
        uses: ./.github/actions/python-install
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ inputs.poetry-version }}
          working-directory: ${{ inputs.working-directory }}
          delete-poetry-lock: ${{ inputs.delete-poetry-lock }}

        #----------------------------------------------
        # build documentation
        #----------------------------------------------
      - name: build documentation
        run: |
          poetry run mkdocs build
          
        #----------------------------------------------
        # package and upload artifact for deployment to GitHub Pages 
        #----------------------------------------------
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ inputs.working-directory }}/site


        #----------------------------------------------
        # deploy page
        #----------------------------------------------
      - name: Deploy Docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4